### ISSUE TITLE
Unable to process Amex payments on  'Make a repeat payment' & 'Make a repeat preauth'.

### ISSUE THREAD

**Issue by SailathaG** [JudoPay/Judo-ObjC#4]
Unable to process Amex payments on  'Make a repeat payment' &amp; 'Make a repeat preauth'.

https://reports3.testuff.com/view/Judo-Pay-uzemytq42zjbn7vfncctlvrruoqjucyp/run/31f7938ecc098bf2475d01f8aa3a04b1/

System information: 
freeDisk: 266.0
os: Windows 7 Professional
cpu: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
totalRam: 4095.0
freeRam: 4095.0

 
Severity: P3 -Medium

Branch: 1.0
Project: iOS SDK ObjC 4.5.2

Test summary: iOS SDK ObjC 4.5.2

Report defect as closed: https://service3.testuff.com/api/v0/status/Judo-Pay-uzemytq42zjbn7vfncctlvrruoqjucyp/66217a38c44e664507feaa5018d676b2/?status=closed

**Comment by hirenhirani** [comment]
@SailathaG We should consider canning the System Information: that is copied and pasted in every bug as it does not really aid the bug definition. In this case, this is actually an issue on the iOS SDK being tested on the mac.

**Comment by SailathaG** [comment]
Sure thing. I am deleting System Information. And this will not be added to any of our future bugs.
