### ISSUE TITLE
Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by andproff** [JudoPay/Judo-ObjC#6]
Got the same error with 4.5 and 4.5.4 also (I am using pods)

![screen shot 2015-10-05 at 8 29 55 pm](https://cloud.githubusercontent.com/assets/1391561/10288170/e35e06c0-6b9f-11e5-9e64-a539b4f2c953.png)

**Comment by Ryce** [comment]
Hi @andproff,

issue resolved in hot fix release.
[see 4.5.5-beta](https://github.com/JudoPay/Judo-ObjC/releases/tag/4.5.5-beta)

you can also use cocoa pods

```
pod 'JudoSDK', '~> 4.5.5-beta'
```

found the issue and removed the Bundle Executable Key from the JudoPay Bundle resource plist. everything should work fine now

**Comment by andproff** [comment]
Hello @Ryce thank you 
now working like a charm
